# Generated by Django 5.2.6 on 2025-09-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Полное название фильма', max_length=200, verbose_name='Название фильма')),
                ('year', models.IntegerField(help_text='Год выхода фильма', verbose_name='Год выпуска')),
                ('director', models.CharField(help_text='ФИО режиссера', max_length=100, verbose_name='Режиссер')),
                ('actors', models.TextField(help_text='Список актеров через запятую', verbose_name='Актеры')),
                ('genre', models.CharField(help_text='Основной жанр фильма', max_length=100, verbose_name='Жанр')),
                ('description', models.TextField(blank=True, help_text='Краткое описание сюжета', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['-created_at'],
            },
        ),
    ]
