version: '3.8'

services:
  filmbot:
    build: .
    container_name: film_bot_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/film_bot  
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=film_bot.settings
    restart: unless-stopped

volumes:
  sqlite_data: